SELECT  car.CAR_ID, car.CAR_TYPE, ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE * 0.01)) FEE
FROM    CAR_RENTAL_COMPANY_CAR car
LEFT JOIN    (SELECT CAR_TYPE, DISCOUNT_RATE
        FROM    CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE   DURATION_TYPE='30일 이상') plan
ON      car.CAR_TYPE=plan.CAR_TYPE
WHERE   car.CAR_TYPE IN ('세단', 'SUV') 
        AND car.CAR_ID NOT IN (SELECT  DISTINCT CAR_ID
                        FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE   start_date <= '2022-11-30' AND end_date >= '2022-11-1')
        AND ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE * 0.01)) >= 500000 
        AND ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE * 0.01)) < 2000000
        
ORDER BY   FEE DESC, car.CAR_TYPE, car.CAR_ID DESC;